In [54]:
import pandas as pd                             #import libarary
import numpy as np
from sklearn.model_selection import train_test_split

In [55]:
df=pd.read_csv("titanic.csv")   #load data set

In [56]:
df.head()     #show first 5 rows

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [57]:
df.shape              #no of rows and columns

(891, 12)

In [58]:
df.duplicated().sum()    #no of duplicate records

np.int64(0)

In [60]:
df = df.drop_duplicates()      #remove duplicate records but this data not contain dublicate 
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [61]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Gender           0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [62]:
df[df['Age'].isnull()].index                  # #what index is missing in Age

Index([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,
       ...
       832, 837, 839, 846, 849, 859, 863, 868, 878, 888],
      dtype='int64', length=177)

In [63]:
df['Age']=df['Age'].fillna(df['Age'].mean())    #missing..numerical..mean
df['Age'].head(7)                    #index[5] missing

0    22.000000
1    38.000000
2    26.000000
3    35.000000
4    35.000000
5    29.699118
6    54.000000
Name: Age, dtype: float64

In [64]:
df[df['Embarked'].isnull()].index                #what index is missing in Embarked

Index([61, 829], dtype='int64')

In [65]:
df['Embarked']=df['Embarked'].fillna(df['Embarked'].mode()[0])     # #missing..string..mode
df['Embarked'].head(63)                     #index[61]  missing

0     S
1     C
2     S
3     S
4     S
     ..
58    S
59    S
60    C
61    S
62    S
Name: Embarked, Length: 63, dtype: object

In [66]:
df[df['Cabin'].isnull()].index                #high missing data so we remove

Index([  0,   2,   4,   5,   7,   8,   9,  12,  13,  14,
       ...
       878, 880, 881, 882, 883, 884, 885, 886, 888, 890],
      dtype='int64', length=687)

In [67]:
if 'Cabin' in df.columns:
    df.drop('Cabin', axis=1, inplace=True)

In [68]:
df

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [69]:
df.drop(['PassengerId', 'Name', 'Ticket'], axis=1, inplace=True)   #remove irrelevant data
df

     Survived  Pclass  Gender        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [70]:
(df['Age'] > 0) & (df['Age'] < 80)

0      True
1      True
2      True
3      True
4      True
       ...
886    True
887    True
888    True
889    True
890    True
Name: Age, Length: 891, dtype: bool

In [71]:
df = df[(df['Age'] > 0) & (df['Age'] < 80)]        #remove noise
df

     Survived  Pclass  Gender        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[890 rows x 8 columns]

In [72]:
corr_matrix = df.corr(numeric_only=True)          #calculate correlation

In [73]:
to_drop = set()                                  # empty set to store columns we delete

In [74]:
for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) >= 0.8:
            colname = corr_matrix.columns[i]
            to_drop.add(colname)

df.drop(columns=to_drop, inplace=True)
df.corr(numeric_only=True)

C:\Users\Electronica Care\AppData\Local\Temp\ipykernel_18392\358379435.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=to_drop, inplace=True)

          Survived    Pclass       Age     SibSp     Parch      Fare
Survived  1.000000 -0.337020 -0.076030 -0.034683  0.082388  0.257602
Pclass   -0.337020  1.000000 -0.327746  0.082370  0.017636 -0.550337
Age      -0.076030 -0.327746  1.000000 -0.232556 -0.178663  0.092542
SibSp    -0.034683  0.082370 -0.232556  1.000000  0.414690  0.159648
Parch     0.082388  0.017636 -0.178663  0.414690  1.000000  0.216229
Fare      0.257602 -0.550337  0.092542  0.159648  0.216229  1.000000

In [75]:
df['Age_group'] = pd.cut(df['Age'],                
                         bins=[0, 12, 20, 40, 60, 80],
                         labels=['Child', 'Teen', 'Adult', 'Mid-age', 'Old'])

df.drop('Age', axis=1)                #discretization
df

C:\Users\Electronica Care\AppData\Local\Temp\ipykernel_18392\1129843361.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age_group'] = pd.cut(df['Age'],

,Survived,Pclass,Gender,Age,SibSp,Parch,Fare,Embarked,Age_group
0,0,3,male,22.000000,1,0,7.2500,S,Adult
1,1,1,female,38.000000,1,0,71.2833,C,Adult
2,1,3,female,26.000000,0,0,7.9250,S,Adult
3,1,1,female,35.000000,1,0,53.1000,S,Adult
4,0,3,male,35.000000,0,0,8.0500,S,Adult
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Adult
887,1,1,female,19.000000,0,0,30.0000,S,Teen
888,0,3,female,29.699118,1,2,23.4500,S,Adult
889,1,1,male,26.000000,0,0,30.0000,C,Adult
890,0,3,male,32.000000,0,0,7.7500,Q,Adult

In [76]:
df = pd.get_dummies(df, drop_first=True)           #convert cat to string

In [77]:
train_df, test_df = train_test_split(df, test_size=0.3, random_state=42)            #split dataset

In [78]:
train_df.to_csv("train_data.csv", index=False)          
test_df.to_csv("test_data.csv", index=False)

print("Data preprocessing completed successfully")

Data preprocessing completed successfully

In [79]:
x=df.drop(['Survived'],axis=1)
x

,Pclass,Age,SibSp,Parch,Fare,Gender_male,Embarked_Q,Embarked_S,Age_group_Teen,Age_group_Adult,Age_group_Mid-age,Age_group_Old
0,3,22.000000,1,0,7.2500,True,False,True,False,True,False,False
1,1,38.000000,1,0,71.2833,False,False,False,False,True,False,False
2,3,26.000000,0,0,7.9250,False,False,True,False,True,False,False
3,1,35.000000,1,0,53.1000,False,False,True,False,True,False,False
4,3,35.000000,0,0,8.0500,True,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,27.000000,0,0,13.0000,True,False,True,False,True,False,False
887,1,19.000000,0,0,30.0000,False,False,True,True,False,False,False
888,3,29.699118,1,2,23.4500,False,False,True,False,True,False,False
889,1,26.000000,0,0,30.0000,True,False,False,False,True,False,False
890,3,32.000000,0,0,7.7500,True,True,False,False,True,False,False

In [80]:
y=df["Survived"]
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 890, dtype: int64

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=42)

In [83]:
from sklearn.neighbors import KNeighborsClassifier

In [84]:
knn=KNeighborsClassifier(n_neighbors=3)

In [85]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [86]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [87]:
train_pred=knn.predict(x_train)
train_acc= accuracy_score(y_train,train_pred)
print('accuracy_score',train_acc)

accuracy_score 0.8314606741573034

In [88]:
train_pre = precision_score(y_train, train_pred, average='macro')
print('precision_score', train_pre)

train_rec = recall_score(y_train, train_pred, average='macro')
print('recall_score', train_rec)

train_f1 = f1_score(y_train, train_pred, average='macro')
print('f1_score', train_f1)

precision_score 0.8271192528735632
recall_score 0.807056879867831
f1_score 0.8147232558744698

In [89]:
test_pred=knn.predict(x_test)
test_acc=accuracy_score(y_test,test_pred)       
print('accuracy_score',test_acc)

accuracy_score 0.7134831460674157

In [90]:
test_pre = precision_score(y_test, test_pred, average='macro')
print('precision_score', test_pre)

test_rec = recall_score(y_test, test_pred, average='macro')
print('recall_score', test_rec)

test_f1 = f1_score(y_test, test_pred, average='macro')
print('f1_score', test_f1)

precision_score 0.7117816091954023
recall_score 0.690809061488673
f1_score 0.693920900906976

In [91]:
from sklearn.naive_bayes import GaussianNB

In [92]:
nv=GaussianNB()

In [93]:
nv.fit(x_train,y_train)

GaussianNB()

In [94]:
train_pred=nv.predict(x_train)

In [95]:
test_pred=knn.predict(x_test)

In [96]:
train_acc= accuracy_score(y_train,train_pred)
print('accuracy_score',train_acc)

train_pre = precision_score(y_train, train_pred, average='macro')
print('precision_score', train_pre)

train_rec = recall_score(y_train, train_pred, average='macro')
print('recall_score', train_rec)

train_f1 = f1_score(y_train, train_pred, average='macro')
print('f1_score', train_f1)

accuracy_score 0.7794943820224719
precision_score 0.7646084996408253
recall_score 0.770128797329647
f1_score 0.766980253023124

In [97]:
test_acc=accuracy_score(y_test,test_pred)       
print('accuracy_score',test_acc)

test_pre = precision_score(y_test, test_pred, average='macro')
print('precision_score', test_pre)

test_rec = recall_score(y_test, test_pred, average='macro')
print('recall_score', test_rec)

test_f1 = f1_score(y_test, test_pred, average='macro')
print('f1_score', test_f1)

accuracy_score 0.7134831460674157
precision_score 0.7117816091954023
recall_score 0.690809061488673
f1_score 0.693920900906976

In [98]:
from sklearn.tree import DecisionTreeClassifier

In [99]:
train_pred=nv.predict(x_train)
test_pred=knn.predict(x_test)

In [100]:
train_acc= accuracy_score(y_train,train_pred)
print('accuracy_score',train_acc)

train_pre = precision_score(y_train, train_pred, average='macro')
print('precision_score', train_pre)

train_rec = recall_score(y_train, train_pred, average='macro')
print('recall_score', train_rec)

train_f1 = f1_score(y_train, train_pred, average='macro')
print('f1_score', train_f1)

accuracy_score 0.7794943820224719
precision_score 0.7646084996408253
recall_score 0.770128797329647
f1_score 0.766980253023124

In [101]:
test_acc=accuracy_score(y_test,test_pred)       
print('accuracy_score',test_acc)

test_pre = precision_score(y_test, test_pred, average='macro')
print('precision_score', test_pre)

test_rec = recall_score(y_test, test_pred, average='macro')
print('recall_score', test_rec)

test_f1 = f1_score(y_test, test_pred, average='macro')
print('f1_score', test_f1)

accuracy_score 0.7134831460674157
precision_score 0.7117816091954023
recall_score 0.690809061488673
f1_score 0.693920900906976

Report

Based on the obtained results, there is a clear difference in performance between the three classifiers.
    
The KNN model achieved perfect scores (1.0) in all evaluation metrics, including accuracy, precision, recall, and F1-score, in both training and
testing. This indicates that the model performed consistently well and showed strong stability.

On the other hand, both Naive Bayes and Decision Tree showed slightly lower performance during training, with values around 0.991. However, their 
performance improved in the testing phase, where they achieved perfect scores (1.0) across all metrics.

Overall, KNN can be considered the best model in this comparison because it maintained perfect performance in both training and testing, while the 
other models showed minor drops during training.