In [1]:
import pandas as pd

In [3]:
data=pd.read_csv('car_price.csv')
data.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0

In [5]:
x=data.drop('selling_price',axis=1)
x

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,Hyundai i20 Sportz Diesel,2010,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,Maruti Swift VXI BSIII,2007,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0
...,...,...,...,...,...,...,...,...,...,...,...
95,Hyundai i20 Asta Optional with Sunroof 1.2,2013,61500,Petrol,Dealer,Manual,First Owner,18.50,1197.0,82.85,5.0
96,Maruti Swift Dzire LDI,2016,150000,Diesel,Individual,Manual,First Owner,26.59,1248.0,74.00,5.0
97,Hyundai Xcent 1.2 Kappa SX Option AT,2016,72000,Petrol,Dealer,Automatic,First Owner,19.10,1197.0,82.00,5.0
98,Maruti Alto LX BSIII,2008,68000,Petrol,Dealer,Manual,Third Owner,19.70,796.0,46.30,5.0
99,Hyundai i20 1.4 Asta Option,2017,110000,Diesel,Individual,Manual,First Owner,22.54,1396.0,88.73,5.0

In [6]:
y=data['selling_price']
y

0     450000
1     370000
2     158000
3     225000
4     130000
       ...
95    525000
96    600000
97    565000
98    120000
99    725000
Name: selling_price, Length: 100, dtype: int64

In [7]:
y.value_counts()

selling_price
450000    4
500000    4
425000    4
600000    4
150000    4
         ..
535000    1
175000    1
565000    1
120000    1
725000    1
Name: count, Length: 74, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=30)

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [3]:
rf=RandomForestClassifier(n_estimators=100)

In [9]:
rf.fit(x_train,y_train)

NameError: name 'x_train' is not defined